server:
  port: 8083
spring:
  datasource:
    minIdle: 10
    maxActive: 50
    maxLifetime: 180000
    idleTimeout: 60000
  datasource0:
    url: jdbc:mysql://localhost:3306/sharding01?useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  datasource1:
    url: jdbc:mysql://localhost:3306/sharding02?useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
